#ifndef _CONFIG_H_
#define _CONFIG_H_

#ifdef __cplusplus
extern "C" {
#endif

#define GATEWAY_WIFI_MODE WIFI_MODE_APSTA
#define GATEWAY_WIFI_IF ESP_IF_WIFI_AP
#define GATEWAY_WIFI_CHANNEL_DEFAULT CONFIG_ESPNOW_CHANNEL
#define GATEWAY_WIFI_SSID CONFIG_ESPNOW_WIFI_SSID
#define GATEWAY_WIFI_PASSWORD CONFIG_ESPNOW_WIFI_PASSWORD

#define GATEWAY_MDNS_NAME CONFIG_ESPNOW_MDNS_NAME
#define GATEWAY_MDNS_INSTANCE_NAME CONFIG_ESPNOW_MDNS_INSTANCE_NAME
#define GATEWAY_HTTP_PORT CONFIG_ESPNOW_HTTP_PORT
#define GATEWAY_HTTP_AUTH_USER CONFIG_ESPNOW_HTTP_AUTH_USER
#define GATEWAY_HTTP_AUTH_PASSWORD CONFIG_ESPNOW_HTTP_AUTH_PASSWORD

#define GATEWAY_BROKER_URL CONFIG_ESPNOW_BROKER_URL
#define GATEWAY_BROKER_USERNAME CONFIG_ESPNOW_BROKER_USERNAME
#define GATEWAY_BROKER_PASSWORD CONFIG_ESPNOW_BROKER_PASSWORD
#define GATEWAY_BROKER_QOS 0
#define GATEWAY_BROKER_RETAIN 0

#ifdef __cplusplus
}
#endif

#endif /* _CONFIG_H_ */
